insert into sede values(5,"Abruzzo","L'aquila","Sulmona");
insert into sede values(6,"Abruzzo","Pescara","Popoli");
insert into sede values(7,"Abruzzo","Chieti","Lanciano");
insert into sede values(8,"Abruzzo","Chieti","Ortona");
insert into sede values(9,"Abruzzo","Chieti","Vasto");
insert into sede values(10,"Abruzzo","L'aquila","Avezzano");
insert into sede values(11,"Abruzzo","L'aquila","Castel di sangro");
insert into sede values(12,"Abruzzo","Teramo","Giulianova");
insert into sede values(13,"Abruzzo","Teramo","Atri");
insert into sede values(16,"Basilicata","Potenza","Venosa");
insert into sede values(17,"Basilicata","Matera","Policoro");
insert into sede values(18,"Basilicata","Matera","Pisticci");
insert into sede values(19,"Basilicata","Potenza","Melfi");
insert into sede values(20,"Basilicata","Potenza","Lagonegro");
insert into sede values(26,"Calabria","Cosenza","Cassano allo ionio");
insert into sede values(27,"Calabria","Cosenza","Belvedere marittimo");
insert into sede values(28,"Calabria","Vibo Valentia","Serra s. bruno");
insert into sede values(29,"Calabria","Reggio Calabria","Melito di porto salvo");
insert into sede values(30,"Calabria","Reggio Calabria","Roccella jonica");
insert into sede values(31,"Calabria","Cosenza","Acri");
insert into sede values(32,"Calabria","Catanzaro","Satriano");
insert into sede values(33,"Calabria","Reggio Calabria","Villa san giovanni");
insert into sede values(34,"Calabria","Catanzaro","Lamezia terme");
insert into sede values(35,"Calabria","Reggio Calabria","Locri");
insert into sede values(36,"Calabria","Cosenza","Paola");
insert into sede values(37,"Calabria","Crotone","Crotone");
insert into sede values(38,"Calabria","Cosenza","Rossano");
insert into sede values(39,"Calabria","Cosenza","Castrovillari");
insert into sede values(40,"Calabria","Reggio Calabria","Palmi");
insert into sede values(46,"Campania","Caserta","Piedimonte matese");
insert into sede values(47,"Campania","Salerno","Costa damalfi");
insert into sede values(48,"Campania","Benevento","Cerreto");
insert into sede values(49,"Campania","Salerno","Agropoli  via");
insert into sede values(50,"Campania","Benevento","S.bartolomeo");
insert into sede values(51,"Campania","Avellino","Santangelo dei lombardi");
insert into sede values(52,"Campania","Salerno","Sala consilina");
insert into sede values(53,"Campania","Napoli","Casoria");
insert into sede values(54,"Campania","Napoli","Nola");
insert into sede values(55,"Campania","Avellino","Ariano irpino");
insert into sede values(56,"Campania","Napoli","Pozzuoli");
insert into sede values(57,"Campania","Salerno","Vallo della lucania");
insert into sede values(58,"Campania","Caserta","Aversa");
insert into sede values(59,"Campania","Caserta","Sessa aurunca");
insert into sede values(60,"Campania","Salerno","Pagani");
insert into sede values(61,"Campania","Napoli","Ischia");
insert into sede values(71,"Emilia-Romagna","Piacenza","Bobbio");
insert into sede values(72,"Emilia-Romagna","Parma","Borgo");
insert into sede values(73,"Emilia-Romagna","Modena","Pavullo nel frignano");
insert into sede values(74,"Emilia-Romagna","Modena","Carpi");
insert into sede values(75,"Emilia-Romagna","Bologna","Imola");
insert into sede values(76,"Emilia-Romagna","Ravenna","Faenza");
insert into sede values(77,"Emilia-Romagna","Ravenna","Lugo");
insert into sede values(78,"Emilia-Romagna","Modena","Sassuolo");
insert into sede values(79,"Emilia-Romagna","Ferrara","Comacchio");
insert into sede values(80,"Emilia-Romagna","Forli-Cesena","Forli");
insert into sede values(81,"Emilia-Romagna","Parma","Fidenza");
insert into sede values(82,"Emilia-Romagna","Forli-Cesena","Cesena");
insert into sede values(83,"Emilia-Romagna","Ferrara","Cento");
insert into sede values(88,"Friuli-Venezia Giulia","Udine","Latisana");
insert into sede values(89,"Friuli-Venezia Giulia","Udine","Gemona del griuli");
insert into sede values(90,"Friuli-Venezia Giulia","Pordenone","Maniago");
insert into sede values(91,"Friuli-Venezia Giulia","Gorizia","Monfalcone");
insert into sede values(92,"Friuli-Venezia Giulia","Udine","Cervignano del friuli");
insert into sede values(93,"Friuli-Venezia Giulia","Udine","Tolmezzo");
insert into sede values(94,"Friuli-Venezia Giulia","Gorizia","Gorizia");
insert into sede values(100,"Lazio","Roma","Nettuno");
insert into sede values(101,"Lazio","Roma","Anzio");
insert into sede values(102,"Lazio","Roma","Civitavecchia");
insert into sede values(103,"Lazio","Roma","Palestrina");
insert into sede values(104,"Lazio","Roma","Velletri");
insert into sede values(105,"Lazio","Frosinone","Sora");
insert into sede values(106,"Lazio","Roma","Pomezia");
insert into sede values(107,"Lazio","Roma","Frascati");
insert into sede values(108,"Lazio","Rieti","Rieti");
insert into sede values(109,"Lazio","Viterbo","Viterbo");
insert into sede values(110,"Lazio","Roma","Albano laziale");
insert into sede values(111,"Lazio","Latina","Formia");
insert into sede values(112,"Lazio","Roma","Tivoli");
insert into sede values(113,"Lazio","Frosinone","Cassino");
insert into sede values(118,"Liguria","Savona","Albenga");
insert into sede values(119,"Liguria","Imperia","Sanremo");
insert into sede values(120,"Liguria","Genova","Chiavari");
insert into sede values(133,"Lombardia","Bergamo","Lovere");
insert into sede values(134,"Lombardia","Cremona","Soresina");
insert into sede values(135,"Lombardia","Bergamo","Zogno");
insert into sede values(136,"Lombardia","Varese","Luino");
insert into sede values(137,"Lombardia","Como","Menaggio");
insert into sede values(138,"Lombardia","Pavia","Mede");
insert into sede values(139,"Lombardia","Bergamo","Romano di lombardia");
insert into sede values(140,"Lombardia","Sondrio","Tirano");
insert into sede values(141,"Lombardia","Mantova","Suzzara");
insert into sede values(142,"Lombardia","Milano","Legnano");
insert into sede values(143,"Lombardia","Pavia","Mortara");
insert into sede values(144,"Lombardia","Como","Cantu");
insert into sede values(145,"Lombardia","Milano","Gorgonzola");
insert into sede values(146,"Lombardia","Monza E Brianza","Desio");
insert into sede values(147,"Lombardia","Brescia","Montichiari");
insert into sede values(148,"Lombardia","Bergamo","Ponte san pietro");
insert into sede values(149,"Lombardia","Como","Erba");
insert into sede values(150,"Lombardia","Varese","Gavirate");
insert into sede values(151,"Lombardia","Pavia","Voghera");
insert into sede values(152,"Lombardia","Varese","Saronno");
insert into sede values(153,"Lombardia","Brescia","Gardone val trompia");
insert into sede values(154,"Lombardia","Lecco","Merate");
insert into sede values(155,"Lombardia","Monza E Brianza","Monza");
insert into sede values(156,"Lombardia","Milano","Cinisello balsamo");
insert into sede values(157,"Lombardia","Varese","Gallarate");
insert into sede values(158,"Lombardia","Lodi","Codogno");
insert into sede values(159,"Lombardia","Brescia","Chiari");
insert into sede values(160,"Lombardia","Varese","Busto arsizio");
insert into sede values(161,"Lombardia","Sondrio","Morbegno");
insert into sede values(162,"Lombardia","Milano","Rho");
insert into sede values(163,"Lombardia","Pavia","Stradella");
insert into sede values(164,"Lombardia","Bergamo","Clusone");
insert into sede values(165,"Lombardia","Brescia","Verolanuova");
insert into sede values(166,"Lombardia","Bergamo","Treviglio");
insert into sede values(167,"Lombardia","Cremona","Crema");
insert into sede values(168,"Lombardia","Brescia","Salo");
insert into sede values(169,"Lombardia","Brescia","Breno");
insert into sede values(170,"Lombardia","Pavia","Vigevano");
insert into sede values(171,"Lombardia","Monza E Brianza","Vimercate");
insert into sede values(172,"Lombardia","Mantova","Castiglione delle stiviere");
insert into sede values(173,"Lombardia","Cremona","Casalmaggiore");
insert into sede values(179,"Marche","Macerata","Camerino");
insert into sede values(180,"Marche","Macerata","Civitanova marche");
insert into sede values(181,"Marche","Ancona","Fabriano");
insert into sede values(182,"Marche","Macerata","Recanati");
insert into sede values(183,"Marche","Pesaro E Urbino","Fano");
insert into sede values(184,"Marche","Pesaro E Urbino","Pesaro");
insert into sede values(185,"Marche","Pesaro E Urbino","Urbino");
insert into sede values(186,"Marche","Macerata","Tolentino");
insert into sede values(187,"Marche","Ascoli Piceno","San benedetto del tronto");
insert into sede values(188,"Marche","Ancona","Senigallia");
insert into sede values(189,"Marche","Ancona","Jesi");
insert into sede values(192,"Molise","Campobasso","Termoli");
insert into sede values(201,"Piemonte","Asti","Canelli");
insert into sede values(202,"Piemonte","Novara","Arona");
insert into sede values(203,"Piemonte","Torino","Savigliano");
insert into sede values(204,"Piemonte","Cuneo","Bra");
insert into sede values(205,"Piemonte","Verbano-cusio-ossola","Domodossola");
insert into sede values(206,"Piemonte","Alessandria","Ovada");
insert into sede values(207,"Piemonte","Alessandria","Tortona");
insert into sede values(208,"Piemonte","Torino","Cirie");
insert into sede values(209,"Piemonte","Torino","Rivoli");
insert into sede values(210,"Piemonte","Cueno","Alba");
insert into sede values(211,"Piemonte","Torino","Moncalieri");
insert into sede values(212,"Piemonte","Torino","Pinerolo");
insert into sede values(213,"Piemonte","Torino","Cuorgne");
insert into sede values(214,"Piemonte","Alessandria","Acqui terme");
insert into sede values(215,"Piemonte","Alessandria","Novi ligure");
insert into sede values(216,"Piemonte","Novara","Borgomanero");
insert into sede values(217,"Piemonte","Vercelli","Borgosesia");
insert into sede values(218,"Piemonte","Torino","Ivrea");
insert into sede values(219,"Piemonte","Torino","Chivasso");
insert into sede values(220,"Piemonte","Verbano-cusio-ossola","Verbania");
insert into sede values(221,"Piemonte","Torino","Susa");
insert into sede values(222,"Piemonte","Alessandria","Casale monferrato");
insert into sede values(223,"Piemonte","Cuneo","Mondovi");
insert into sede values(224,"Piemonte","Cuneo","Saluzzo");
insert into sede values(231,"Puglia","Lecce","Gallipoli");
insert into sede values(232,"Puglia","Barletta-andria-trani","Barletta");
insert into sede values(233,"Puglia","Lecce","Maglie");
insert into sede values(234,"Puglia","Bari","Gioia del colle");
insert into sede values(235,"Puglia","Barletta-andria-trani","Trani");
insert into sede values(236,"Puglia","Foggia","Cerignola");
insert into sede values(237,"Puglia","Foggia","Lucera");
insert into sede values(238,"Puglia","Brrindisi","Ostuni");
insert into sede values(239,"Puglia","Foggia","Manfredonia");
insert into sede values(240,"Puglia","Lecce","Casarano");
insert into sede values(241,"Puglia","Foggia","San severo");
insert into sede values(246,"Sardegna","Nuoro","Macomer");
insert into sede values(247,"Sardegna","Sud Sardegna","Isili");
insert into sede values(248,"Sardegna","Sassari","Ozieri");
insert into sede values(249,"Sardegna","Sassari","Alghero");
insert into sede values(250,"Sardegna","Sud Sardegna","Sanluri");
insert into sede values(251,"Sardegna","Nuoro","Lanusei");
insert into sede values(252,"Sardegna","Sud Sardegna","Iglesias");
insert into sede values(253,"Sardegna","Sassari","Olbia");
insert into sede values(254,"Sardegna","Sassari","Tempio pausania");
insert into sede values(264,"Sicilia","Catania","Adrano");
insert into sede values(265,"Sicilia","Agrigento","Licata");
insert into sede values(266,"Sicilia","Trapani","Alcamo");
insert into sede values(267,"Sicilia","Messina","Mistretta");
insert into sede values(268,"Sicilia","Caltanissetta","Mussomeli");
insert into sede values(269,"Sicilia","Palermo","Cefalu");
insert into sede values(270,"Sicilia","Trapani","Pantelleria");
insert into sede values(271,"Sicilia","Messina","Patti");
insert into sede values(272,"Sicilia","Palermo","Corleone");
insert into sede values(273,"Sicilia","Messina","Lipari");
insert into sede values(274,"Sicilia","Palermo","Partinico");
insert into sede values(275,"Sicilia","Palermo","Lercara friddi");
insert into sede values(276,"Sicilia","Enna","Nicosia");
insert into sede values(277,"Sicilia","Trapani","Castelvetrano");
insert into sede values(278,"Sicilia","Agrigento","Canicatti");
insert into sede values(279,"Sicilia","Agrigento","Sciacca");
insert into sede values(280,"Sicilia","Siracusa","Noto");
insert into sede values(281,"Sicilia","Catania","Caltagirone");
insert into sede values(282,"Sicilia","Palermo","Bagheria");
insert into sede values(283,"Sicilia","Messina","Taormina");
insert into sede values(284,"Sicilia","Ragusa","Vittoria");
insert into sede values(285,"Sicilia","Catania","Giarre");
insert into sede values(286,"Sicilia","Messina","Santagata di militello");
insert into sede values(287,"Sicilia","Ragusa","Modica");
insert into sede values(288,"Sicilia","Messina","Barcellona pozzo di gotto");
insert into sede values(289,"Sicilia","Palermo","Termini imerese");
insert into sede values(290,"Sicilia","Caltanissetta","Gela");
insert into sede values(291,"Sicilia","Trapani","Marsala");
insert into sede values(292,"Sicilia","Catania","Acireale");
insert into sede values(303,"Toscana","Arezzo","Cortona");
insert into sede values(304,"Toscana","Massa Carrara","Pontremoli");
insert into sede values(305,"Toscana","Pisa","Volterra");
insert into sede values(306,"Toscana","Massa Carrara","Massa");
insert into sede values(307,"Toscana","Livorno","Cecina");
insert into sede values(308,"Toscana","Lucca","Borgo a mozzano");
insert into sede values(309,"Toscana","Lucca","Pietrasanta");
insert into sede values(310,"Toscana","Arezzo","Poppi");
insert into sede values(311,"Toscana","Grosseto","Pollonica");
insert into sede values(312,"Toscana","Pisa","Pontedera");
insert into sede values(313,"Toscana","Livorno","Portoferraio");
insert into sede values(314,"Toscana","Pisa","San miniato");
insert into sede values(315,"Toscana","Arezzo","Montevarchi");
insert into sede values(316,"Toscana","Arezzo","Sansepolcro");
insert into sede values(317,"Toscana","Grosseto","Orbetello");
insert into sede values(318,"Toscana","Siena","Poggibonsi");
insert into sede values(319,"Toscana","Livorno","Piombino");
insert into sede values(320,"Toscana","Lucca","Viareggio");
insert into sede values(321,"Toscana","Siena","Montepulciano");
insert into sede values(322,"Toscana","Pistoia","Pescia");
insert into sede values(323,"Toscana","Firenze","Borgo san lorenzo");
insert into sede values(324,"Toscana","Firenze","Empoli");
insert into sede values(325,"Toscana","Lucca","Castelnuovo di garfagnana");
insert into sede values(326,"Toscana","Massa Carrara","Aulla");
insert into sede values(327,"Toscana","Siena","Piccolomini");
insert into sede values(330,"Trentino-alto Adige","Trento","Rovereto");
insert into sede values(331,"Trentino-alto Adige","Trento","Tiote di trento");
insert into sede values(332,"Trentino-alto Adige","Bolzano","Merano");
insert into sede values(333,"Trentino-alto Adige","Trento","Cavalese");
insert into sede values(334,"Trentino-alto Adige","Trento","Cles");
insert into sede values(335,"Trentino-alto Adige","Bolzano","Bressanone");
insert into sede values(336,"Trentino-alto Adige","Trento","Valsugnana");
insert into sede values(337,"Trentino-alto Adige","Trento","Riva del garda");
insert into sede values(340,"Umbria","Terni","Amelia");
insert into sede values(341,"Umbria","Perugia","Gualdo tadino");
insert into sede values(342,"Umbria","Perugia","Spoleto");
insert into sede values(343,"Umbria","Perugia","Citta di castello");
insert into sede values(344,"Umbria","Perugia","Foligno");
insert into sede values(345,"Umbria","Terni","Orvieto");
insert into sede values(347,"Valle D'aosta","Aosta","Chatillon");
insert into sede values(355,"Veneto","Rovigo","Badia polesine");
insert into sede values(356,"Veneto","Verona","Caprino veronese");
insert into sede values(357,"Veneto","Treviso","Oderzo");
insert into sede values(358,"Veneto","Belluno","Pieve di cadore");
insert into sede values(359,"Veneto","Vicenza","Thiene");
insert into sede values(360,"Veneto","Treviso","Montebelluna");
insert into sede values(361,"Veneto","Padova","Cittadella");
insert into sede values(362,"Veneto","Venezia","Portoguaro");
insert into sede values(363,"Veneto","Vicenza","Valdagno");
insert into sede values(364,"Veneto","Verona","Legnago");
insert into sede values(365,"Veneto","Verona","Soave");
insert into sede values(366,"Veneto","Venezia","Chioggia");
insert into sede values(367,"Veneto","Belluno","Feltre");
insert into sede values(368,"Veneto","Rovigo","Adria");
insert into sede values(369,"Veneto","Vicenza","Bassano del grappa");
insert into sede values(370,"Veneto","Padova","Este");
insert into sede values(371,"Veneto","Treviso","Conegliano");
insert into sede values(372,"Veneto","Venezia","San dona di piave");
insert into sede values(1,"Abruzzo","Chieti",NULL);
insert into sede values(2,"Abruzzo","Teramo",NULL);
insert into sede values(3,"Abruzzo","Pescara",NULL);
insert into sede values(4,"Abruzzo","L'aquila",NULL);
insert into sede values(14,"Basilicata","Potenza",NULL);
insert into sede values(15,"Basilicata","Matera",NULL);
insert into sede values(21,"Calabria","Crotone",NULL);
insert into sede values(22,"Calabria","Vibo Valentia",NULL);
insert into sede values(23,"Calabria","Catanzaro",NULL);
insert into sede values(24,"Calabria","Cosenza",NULL);
insert into sede values(25,"Calabria","Reggio Calabria",NULL);
insert into sede values(41,"Campania","Napoli",NULL);
insert into sede values(42,"Campania","Caserta",NULL);
insert into sede values(43,"Campania","Avellino",NULL);
insert into sede values(44,"Campania","Benevento",NULL);
insert into sede values(45,"Campania","Salerno",NULL);
insert into sede values(62,"Emilia-Romagna","Modena",NULL);
insert into sede values(63,"Emilia-Romagna","Bologna",NULL);
insert into sede values(64,"Emilia-Romagna","Forli-Cesena",NULL);
insert into sede values(65,"Emilia-Romagna","Rimini",NULL);
insert into sede values(66,"Emilia-Romagna","Ravenna",NULL);
insert into sede values(67,"Emilia-Romagna","Reggio Emilia",NULL);
insert into sede values(68,"Emilia-Romagna","Ferrara",NULL);
insert into sede values(69,"Emilia-Romagna","Parma",NULL);
insert into sede values(70,"Emilia-Romagna","Piacenza",NULL);
insert into sede values(84,"Friuli-Venezia Giulia","Udine",NULL);
insert into sede values(85,"Friuli-Venezia Giulia","Gorizia",NULL);
insert into sede values(86,"Friuli-Venezia Giulia","Trieste",NULL);
insert into sede values(87,"Friuli-Venezia Giulia","Pordenone",NULL);
insert into sede values(95,"Lazio","Frosinone",NULL);
insert into sede values(96,"Lazio","Roma",NULL);
insert into sede values(97,"Lazio","Latina",NULL);
insert into sede values(98,"Lazio","Viterbo",NULL);
insert into sede values(99,"Lazio","Rieti",NULL);
insert into sede values(114,"Liguria","Savona",NULL);
insert into sede values(115,"Liguria","La Spezia",NULL);
insert into sede values(116,"Liguria","Genova",NULL);
insert into sede values(117,"Liguria","Imperia",NULL);
insert into sede values(121,"Lombardia","Brescia",NULL);
insert into sede values(122,"Lombardia","Varese",NULL);
insert into sede values(123,"Lombardia","Lecco",NULL);
insert into sede values(124,"Lombardia","Mantova",NULL);
insert into sede values(125,"Lombardia","Milano",NULL);
insert into sede values(126,"Lombardia","Como",NULL);
insert into sede values(127,"Lombardia","Pavia",NULL);
insert into sede values(128,"Lombardia","Cremona",NULL);
insert into sede values(129,"Lombardia","Lodi",NULL);
insert into sede values(130,"Lombardia","Sondrio",NULL);
insert into sede values(131,"Lombardia","Bergamo",NULL);
insert into sede values(132,"Lombardia","Monza E Brianza",NULL);
insert into sede values(174,"Marche","Ancona",NULL);
insert into sede values(175,"Marche","Fermo",NULL);
insert into sede values(176,"Marche","Ascoli Piceno",NULL);
insert into sede values(177,"Marche","Pesaro E Urbino",NULL);
insert into sede values(178,"Marche","Macerata",NULL);
insert into sede values(190,"Molise","Isernia",NULL);
insert into sede values(191,"Molise","Campobasso",NULL);
insert into sede values(193,"Piemonte","Verbano-cusio-ossola",NULL);
insert into sede values(194,"Piemonte","Alessandria",NULL);
insert into sede values(195,"Piemonte","Asti",NULL);
insert into sede values(196,"Piemonte","Vercelli",NULL);
insert into sede values(197,"Piemonte","Torino",NULL);
insert into sede values(198,"Piemonte","Cuneo",NULL);
insert into sede values(199,"Piemonte","Biella",NULL);
insert into sede values(200,"Piemonte","Novara",NULL);
insert into sede values(225,"Puglia","Barletta-andria-trani",NULL);
insert into sede values(226,"Puglia","Lecce",NULL);
insert into sede values(227,"Puglia","Brindisi",NULL);
insert into sede values(228,"Puglia","Bari",NULL);
insert into sede values(229,"Puglia","Foggia",NULL);
insert into sede values(230,"Puglia","Taranto",NULL);
insert into sede values(242,"Sardegna","Nuoro",NULL);
insert into sede values(243,"Sardegna","Oristano",NULL);
insert into sede values(244,"Sardegna","Cagliari",NULL);
insert into sede values(245,"Sardegna","Sassari",NULL);
insert into sede values(255,"Sicilia","Catania",NULL);
insert into sede values(256,"Sicilia","Siracusa",NULL);
insert into sede values(257,"Sicilia","Enna",NULL);
insert into sede values(258,"Sicilia","Trapani",NULL);
insert into sede values(259,"Sicilia","Palermo",NULL);
insert into sede values(260,"Sicilia","Messina",NULL);
insert into sede values(261,"Sicilia","Ragusa",NULL);
insert into sede values(262,"Sicilia","Agrigento",NULL);
insert into sede values(263,"Sicilia","Caltanissetta",NULL);
insert into sede values(293,"Toscana","Pisa",NULL);
insert into sede values(294,"Toscana","Livorno",NULL);
insert into sede values(295,"Toscana","Massa Carrara",NULL);
insert into sede values(296,"Toscana","Siena",NULL);
insert into sede values(297,"Toscana","Grosseto",NULL);
insert into sede values(298,"Toscana","Lucca",NULL);
insert into sede values(299,"Toscana","Pistoia",NULL);
insert into sede values(300,"Toscana","Arezzo",NULL);
insert into sede values(301,"Toscana","Firenze",NULL);
insert into sede values(302,"Toscana","Prato",NULL);
insert into sede values(328,"Trentino-alto Adige","Trento",NULL);
insert into sede values(329,"Trentino-alto Adige","Bolzano",NULL);
insert into sede values(338,"Umbria","Terni",NULL);
insert into sede values(339,"Umbria","Perugia",NULL);
insert into sede values(346,"Valle D'aosta","Aosta",NULL);
insert into sede values(348,"Veneto","Padova",NULL);
insert into sede values(349,"Veneto","Treviso",NULL);
insert into sede values(350,"Veneto","Rovigo",NULL);
insert into sede values(351,"Veneto","Belluno",NULL);
insert into sede values(352,"Veneto","Verona",NULL);
insert into sede values(353,"Veneto","Vicenza",NULL);
insert into sede values(354,"Veneto","Venezia",NULL);
